const sidebars = {
  tutorialSidebar: [
    { type: 'doc', id: 'intro' },
    {
      type: 'category',
      label: 'Playbooks',
      link: { type: 'generated-index', title: 'Playbooks' },
      items: [{ type: 'autogenerated', dirName: 'playbooks' }],
    },
  ],
};
module.exports = sidebars;
