// Prefer AI/tag-generated sidebar, fall back to autogenerated
let generated
try { generated = require('./sidebars.generated.js') } catch (e) {}

if (generated) {
  module.exports = generated
} else {
  /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
  module.exports = {
    docs: [{ type: 'autogenerated', dirName: '.' }],
  }
}
