name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Node & npm versions (debug)
        run: |
          node -v || true
          npm -v || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Use npm ci if a lockfile exists, otherwise fall back to npm install
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      # Safety net: ensure there's at least one doc so Docusaurus doesn't error
      - name: Ensure docs/intro.md exists
        run: |
          mkdir -p docs
          if [ ! -f docs/intro.md ]; then
            cat > docs/intro.md <<'EOF'
            ---
            id: intro
            title: Welcome to OpenMark
            sidebar_position: 1
            ---
            OpenMark turns long AI chats into reusable Markdown.
            EOF
          fi

      # Build will run "prebuild" first (generates sidebars.generated.js)
      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

